#pragma once

// Internal App.cpp implementation shard.
// Fighter, freeze-watch, and aggregate AppState data used by App.cpp internals.

struct ArenaCharacterRuntime {
    CompatibilityContext compatibility;
    CharacterConstants constants;
    std::vector<HitDefinition> hitDefs;
    std::vector<StateDefinition> stateDefs;
    std::vector<CommandStateEntry> commandEntries;
    std::vector<CommandDefinition> commandDefinitions;
    std::vector<AnimationClip> clips;
    std::vector<DecodedSoundSample> samples;
    std::vector<std::string> victoryQuotes;
    std::string name;
    int paletteNo = 1;
    std::filesystem::path palettePath;
};

struct StateControllerCooldown {
    int controllerId = 0;
    int ticks = 0;
};

struct FighterState {
    float x = 0.0f;
    float y = 0.0f;
    float depthZ = 0.0f;
    float vx = 0.0f;
    float vy = 0.0f;
    float depthVz = 0.0f;
    float triggerY = 0.0f;
    bool arenaDepthModifierHeld = false;
    int arenaDepthModifierLastTapFrame = -100000;
    int arenaDepthSidestepTicks = 0;
    float arenaDepthSidestepVelocity = 0.0f;
    int arenaDepthSidestepDirection = 1;
    int facing = 1;
    int stateNo = 0;
    int stateTime = 0;
    int action = 0;
    int animTick = 0;
    char stateType = 'S';
    char moveType = 'I';
    char physics = 'S';
    bool ctrl = true;
    int hitPauseTicks = 0;
    int hitStunTicks = 0;
    int hitSlideTicks = 0;
    float hitVelocityX = 0.0f;
    float hitVelocityY = 0.0f;
    int getHitAnimType = 0;
    int getHitGroundType = 0;
    int getHitAirType = 0;
    int getHitSlideTime = 0;
    int getHitHitTime = 0;
    int getHitCtrlTime = 0;
    int getHitHitCount = 0;
    int hitRecoverAnim = 5005;
    bool hitFall = false;
    bool hitFallTrip = false;
    bool hitDowned = false;
    bool hitCrouch = false;
    bool hitAirborne = false;
    bool hitFallRecover = true;
    int hitFallRecoverTime = 0;
    bool hitDownRecover = true;
    int hitDownRecoverTime = -1;
    float hitDownVelocityX = 0.0f;
    float hitDownVelocityY = 0.0f;
    int hitFallDamage = 0;
    float hitFallYAccel = 0.0f;
    int hitFallAirAction = 5050;
    float hitFallBounceXVelocity = 0.0f;
    float hitFallBounceYVelocity = -4.5f;
    EnvShakeSpec hitFallEnvShake;
    bool hitFallEnvShakePlayed = false;
    ActivePaletteEffect paletteEffect;
    ActiveTransEffect transEffect;
    ActiveAfterImageEffect afterImage;
    float drawAngle = 0.0f;
    bool angleDrawActive = false;
    float displayOffsetX = 0.0f;
    float displayOffsetY = 0.0f;
    std::string debugClipboard;
    int victoryQuote = -1;
    int paletteNo = 1;
    std::vector<PaletteRemap> paletteRemaps;
    int life = 1000;
    int maxLifeOverride = 0;
    int power = 0;
    int hitCount = 0;
    float defenceMultiplier = 1.0f;
    float attackMultiplier = 1.0f;
    float modeDefenceMultiplier = 1.0f;
    float modeAttackMultiplier = 1.0f;
    int attackDistanceOverride = -1;
    int projectileHitId = -1;
    int projectileHitTicks = 0;
    int projectileContactId = -1;
    int projectileContactTicks = 0;
    int projectileGuardedId = -1;
    int projectileGuardedTicks = 0;
    std::vector<int> appliedHitDefIds;
    std::vector<int> firedStateSoundControllerIds;
    std::vector<int> firedStateRuntimeControllerIds;
    std::vector<int> firedStateRuntimeControllerFrameKeys;
    std::vector<StateControllerCooldown> stateRuntimeControllerCooldowns;
    int hitPauseChangeStateControllerId = 0;
    std::vector<CommandInputFrame> inputHistory;
    bool moveContact = false;
    bool moveHit = false;
    bool moveGuarded = false;
    bool guarding = false;
    bool crouchGuard = false;
    bool onGround = true;
    bool helper = false;
    bool destroyRequested = false;
    int ownerIndex = -1;
    int helperId = 0;
    float scaleX = 1.0f;
    float scaleY = 1.0f;
    int pauseMoveTime = 0;
    int superMoveTime = 0;
    int jumpInputBufferTicks = 0;
    bool jumpInputConsumedWhileHeld = false;
    int jumpBaseAction = 0;
    bool jumpPeakActionApplied = false;
    bool screenBound = true;
    bool screenBoundMoveCameraX = false;
    bool screenBoundMoveCameraY = false;
    bool playerPush = true;
    bool posFreezeX = false;
    bool posFreezeY = false;
    bool customHitState = false;
    int customStateOwnerIndex = -1;
    int actionClipOwnerIndex = -1;
    int prevStateNo = 0;
    int sprPriority = 0;
    int rootBindTicks = 0;
    float rootBindOffsetX = 0.0f;
    float rootBindOffsetY = 0.0f;
    int rootBindFacing = 0;
    std::vector<std::string> assertSpecialFlags;
    std::array<int, 60> vars{};
    std::array<int, 60> sysVars{};
    std::array<float, 40> fvars{};
    std::array<float, 40> sysFvars{};
    float edgeWidthFront = -1.0f;
    float edgeWidthBack = -1.0f;
    float playerWidthFront = -1.0f;
    float playerWidthBack = -1.0f;
    int notHitByTicks = 0;
    std::string notHitByValue;
    int hitByTicks = 0;
    std::string hitByValue;
    int targetIndex = -1;
    int targetHitId = -1;
    int targetTicks = 0;
    int boundByIndex = -1;
    int bindTicks = 0;
    bool targetBindPositionActive = false;
    float targetBindOffsetX = 0.0f;
    float targetBindOffsetY = 0.0f;
    int targetBindFacing = 0;
};

struct FreezeWatchFighterSample {
    float x = 0.0f;
    float y = 0.0f;
    float vx = 0.0f;
    float vy = 0.0f;
    float depthZ = 0.0f;
    int stateNo = 0;
    int stateTime = 0;
    int action = 0;
    int animTick = 0;
    int animElem = 0;
    int life = 0;
    int power = 0;
    int hitPauseTicks = 0;
    int hitStunTicks = 0;
    int pauseMoveTime = 0;
    int superMoveTime = 0;
    int ownerIndex = -1;
    char stateType = 'S';
    char moveType = 'I';
    char physics = 'S';
    bool ctrl = false;
    bool onGround = true;
    bool helper = false;
    bool destroyRequested = false;
};

struct FreezeWatchSnapshot {
    MatchPhase matchPhase = MatchPhase::Fight;
    int matchPhaseTicks = 0;
    int globalPauseTicks = 0;
    int globalPauseOwnerIndex = -1;
    int globalPauseOwnerMoveTicks = 0;
    bool globalPauseIsSuper = false;
    int activeProjectiles = 0;
    int activeEffects = 0;
    std::vector<FreezeWatchFighterSample> fighters;
    std::vector<FreezeWatchFighterSample> helpers;
};

struct FreezeWatchState {
    bool visible = false;
    bool hasSnapshot = false;
    int fighterStalledFrames = 0;
    int poseStalledFrames = 0;
    int lastLogStallFrame = 0;
    int lastLogPoseStallFrame = 0;
    std::string poseStalledLabel;
    std::vector<int> fighterPoseStallFrames;
    std::vector<int> helperPoseStallFrames;
    FreezeWatchSnapshot previous;
};

#include "ShopDemoState.h"

struct AppState {
    std::filesystem::path gameRoot;
    LoadedContentSummary content;
    FrontendState frontend;
    SelectionState selection;
    TrainingState training;
    FightMessageState messages;
    FightDisplayState display;
    ProgressionState progression;
    ControlsSettings controls;
    StoryModeState story;
    ShopDemoState shopDemo;
    TextureSprite storyForwardCueImage;
    std::filesystem::path controlsSavePath;
    bool running = true;
    MainSettings mainSettings;
    FightRoundSettings fightRoundSettings;
    MatchPhase matchPhase = MatchPhase::Fight;
    RoundEndReason roundEndReason = RoundEndReason::None;
    int matchTimerTicks = 99 * 60;
    int matchPhaseTicks = 0;
    int roundWinner = 0;
    std::array<int, 2> roundWins{ 0, 0 };
    int currentRound = 1;
    bool matchComplete = false;
    bool roundScoreApplied = false;
    bool roundPoseApplied = false;
    bool fightSessionPrepared = false;
    bool fightSessionLoadFailed = false;
    LoadingProgressState loadingProgress;
    int globalPauseTicks = 0;
    int globalPauseOwnerIndex = -1;
    int globalPauseOwnerMoveTicks = 0;
    bool globalPauseIsSuper = false;
    ActivePaletteEffect backgroundPaletteEffect;
    EnvColorEffect envColor;
    double accumulator = 0.0;
    mutable FramePerfState framePerf;
    bool suppressFpsCounter = false;
    bool suppressArenaCpu = false;
    int frame = 0;
    WindowPresentationState windowPresentation;
    float cameraX = 0.0f;
    float cameraY = 0.0f;
    float arenaCameraYawDeg = 0.0f;
    float arenaCameraTargetYawDeg = 0.0f;
    FreezeWatchState freezeWatch;
    std::vector<FighterState> fighters = std::vector<FighterState>(2);
    std::vector<FighterState> helpers;
    std::vector<RuntimeProjectile> projectiles;
    ArenaConfig arenaConfig;
    DragonRuntimeMode runtimeMode = DragonRuntimeMode::Dragon;
    CompatibilityContext characterCompatibility;
    CharacterConstants characterConstants;
    int characterPaletteNo = 1;
    std::filesystem::path characterPalettePath;
    int opponentPaletteNo = 1;
    std::filesystem::path opponentPalettePath;
    std::vector<HitDefinition> hitDefs;
    std::vector<StateDefinition> stateDefs;
    std::vector<CommandStateEntry> commandEntries;
    std::vector<CommandDefinition> commandDefinitions;
    mutable std::vector<const CommandStateEntry*> trainingMoveListEntriesCache;
    mutable const CommandStateEntry* trainingMoveListCacheData = nullptr;
    mutable size_t trainingMoveListCacheCount = 0;
    mutable TrainingMoveCategory trainingMoveListCacheCategory = TrainingMoveCategory::All;
    mutable TrainingMoveListTab trainingMoveListCacheTab = TrainingMoveListTab::All;
    mutable bool trainingMoveListCacheValid = false;
    std::vector<AnimationClip> characterClips;
    std::vector<AnimationClip> opponentCharacterClips;
    ArenaCharacterRuntime opponentRuntime;
    std::vector<std::vector<AnimationClip>> arenaFighterClips;
    std::vector<ArenaCharacterRuntime> arenaRuntimes;
    std::vector<AnimationClip> fightFxClips;
    std::vector<RuntimeEffect> runtimeEffects;
    std::vector<std::string> victoryQuotes;
    TextureSprite characterLargePortrait;
    std::vector<TextureSprite> characterIconSprites;
    std::vector<TextureSprite> characterFaceSprites;
    SystemScreenAssets systemScreens;
    CommandInputIconAtlas commandInputIcons;
    TextureSprite commandCompleteCheck;
    std::vector<StageBackgroundElement> stageBackground;
    int stageBackgroundStageIndex = -1;
    AudioState audio;
    std::vector<GamepadDevice> gamepads;
    int trainingShowSelectHoldTicks = 0;
    bool trainingShowSelectHoldFired = false;
};
